//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoHead.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"messageType")]
    public enum messageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KeepkAliveSync", Value=0)]
      KeepkAliveSync = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegisterReq", Value=1)]
      RegisterReq = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegisterRsp", Value=2)]
      RegisterRsp = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginReq", Value=3)]
      LoginReq = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginRsp", Value=4)]
      LoginRsp = 4
    }
  
}