//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoHead.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ENetworkMessage")]
    public enum ENetworkMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KEEP_ALIVE_SYNC", Value=0)]
      KEEP_ALIVE_SYNC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_REQ", Value=1)]
      REGISTER_REQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_RSP", Value=2)]
      REGISTER_RSP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_REQ", Value=3)]
      LOGIN_REQ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RSP", Value=4)]
      LOGIN_RSP = 4
    }
  
}