//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ChangeFriendMsg.proto
// Note: requires additional types generated from: UserData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeFriendSync")]
  public partial class ChangeFriendSync : global::ProtoBuf.IExtensible
  {
    public ChangeFriendSync() {}
    
    private protocol.ChangeFriendSync.ChangeType _changeType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"changeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.ChangeFriendSync.ChangeType changeType
    {
      get { return _changeType; }
      set { _changeType = value; }
    }
    private protocol.UserItem _userItem;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocol.UserItem userItem
    {
      get { return _userItem; }
      set { _userItem = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ChangeType")]
    public enum ChangeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADD", Value=0)]
      ADD = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETE", Value=1)]
      DELETE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UPDATE", Value=2)]
      UPDATE = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}