//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetGroupInfoMsg.proto
// Note: requires additional types generated from: GroupData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGroupInfoReq")]
  public partial class GetGroupInfoReq : global::ProtoBuf.IExtensible
  {
    public GetGroupInfoReq() {}
    
    private string _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGroupInfoRsp")]
  public partial class GetGroupInfoRsp : global::ProtoBuf.IExtensible
  {
    public GetGroupInfoRsp() {}
    
    private protocol.GetGroupInfoRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.GetGroupInfoRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private protocol.GroupItem _groupItem;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protocol.GroupItem groupItem
    {
      get { return _groupItem; }
      set { _groupItem = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUP_NOT_EXIST", Value=2)]
      GROUP_NOT_EXIST = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}