//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetGroupInfoMsg.proto
// Note: requires additional types generated from: GroupData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGroupInfoReq")]
  public partial class GetGroupInfoReq : global::ProtoBuf.IExtensible
  {
    public GetGroupInfoReq() {}
    
    private string _groupId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetGroupInfoRsp")]
  public partial class GetGroupInfoRsp : global::ProtoBuf.IExtensible
  {
    public GetGroupInfoRsp() {}
    
    private protocol.GetGroupInfoRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.GetGroupInfoRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private string _groupId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"groupId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupId
    {
      get { return _groupId; }
      set { _groupId = value; }
    }
    private string _groupName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"groupName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string groupName
    {
      get { return _groupName; }
      set { _groupName = value; }
    }
    private string _createrId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createrId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string createrId
    {
      get { return _createrId; }
      set { _createrId = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _memberId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"memberId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> memberId
    {
      get { return _memberId; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GROUP_NOT_EXIST", Value=2)]
      GROUP_NOT_EXIST = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}