//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GetUserInfoMsg.proto
// Note: requires additional types generated from: UserData.proto
namespace protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoReq")]
  public partial class GetUserInfoReq : global::ProtoBuf.IExtensible
  {
    public GetUserInfoReq() {}
    
    private readonly global::System.Collections.Generic.List<string> _targetUserId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"targetUserId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> targetUserId
    {
      get { return _targetUserId; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetUserInfoRsp")]
  public partial class GetUserInfoRsp : global::ProtoBuf.IExtensible
  {
    public GetUserInfoRsp() {}
    
    private protocol.GetUserInfoRsp.ResultCode _resultCode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resultCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protocol.GetUserInfoRsp.ResultCode resultCode
    {
      get { return _resultCode; }
      set { _resultCode = value; }
    }
    private readonly global::System.Collections.Generic.List<protocol.UserItem> _userItem = new global::System.Collections.Generic.List<protocol.UserItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"userItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protocol.UserItem> userItem
    {
      get { return _userItem; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ResultCode")]
    public enum ResultCode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SUCCESS", Value=0)]
      SUCCESS = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FAIL", Value=1)]
      FAIL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USER_NOT_EXIST", Value=2)]
      USER_NOT_EXIST = 2
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}