//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: ProtoHead.proto
namespace protocol
{
    [global::ProtoBuf.ProtoContract(Name=@"ENetworkMessage")]
    public enum ENetworkMessage
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"KEEP_ALIVE_SYNC", Value=0)]
      KEEP_ALIVE_SYNC = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_REQ", Value=1)]
      REGISTER_REQ = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"REGISTER_RSP", Value=2)]
      REGISTER_RSP = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_REQ", Value=3)]
      LOGIN_REQ = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_RSP", Value=4)]
      LOGIN_RSP = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERSONALSETTINGS_REQ", Value=5)]
      PERSONALSETTINGS_REQ = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PERSONALSETTINGS_RSP", Value=6)]
      PERSONALSETTINGS_RSP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETUSERINFO_REQ", Value=7)]
      GETUSERINFO_REQ = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GETUSERINFO_RSP", Value=8)]
      GETUSERINFO_RSP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDFRIEND_REQ", Value=9)]
      ADDFRIEND_REQ = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ADDFRIEND_RSP", Value=10)]
      ADDFRIEND_RSP = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETEFRIEND_REQ", Value=11)]
      DELETEFRIEND_REQ = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DELETEFRIEND_RSP", Value=12)]
      DELETEFRIEND_RSP = 12
    }
  
}